language: rust

branches:
  only:
  - master
  # Github release tags (for example "v0.9" or "v0.9.1").
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  # Branch names endings with "-release" (for example "0.9.0-release").
  - /-release$/

rust:
- nightly-2018-11-12

env:
  global:
  - SODIUM_VERS=1.0.13
  - CARGO_INCREMENTAL=1
  - DEADLINKS_VERS=0.3.0

cache:
  directories:
  - $HOME/.cargo
  - $HOME/.local
  - $TRAVIS_BUILD_DIR/target

dist: trusty

before_install:
- |
  if [ ! -f "$HOME/.local/lib/libsodium.a" ]; then
    wget "https://github.com/jedisct1/libsodium/releases/download/$SODIUM_VERS/libsodium-$SODIUM_VERS.tar.gz" -t 5 -O "libsodium.tar.gz"
    tar xvf libsodium.tar.gz
    cd libsodium-$SODIUM_VERS
    ./configure --prefix=$HOME/.local
    make
    make install
    cd ..
  fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/.local/lib/pkgconfig

install:
- cargo deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
- rustup component add rustfmt-preview
- rustfmt -V
- rustup component add clippy-preview
- cargo clippy -V

script:
- cargo fmt -- --check
- cargo check
- cargo clippy -- -D warnings
- cargo test --tests
- cargo test --doc
- cargo build --example clients
- |
  cargo clean --doc &&
  rustdoc -- -Z unstable-options --extern-html-root-url exonum=https://docs.rs/exonum/0.9.4 &&
  cargo deadlinks --dir target/doc
